server:
  port: 8082

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    deserialization:
      fail-on-unknown-properties: false

capitole:
  common:
    web:
      client:
        configs:
          starwars-service:
            # from Ms-Tenant
            # http://controlplane-server-ms-tenant-svc.controlplane.svc.cluster.local
            base-url: https://swapi.info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

logbook:
  write:
    chunk-size: 2048

logging:
  level:
    org.zalando.logbook: TRACE
