server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    deserialization:
      fail-on-unknown-properties: false
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      time-to-live: 86400000  # TTL en ms (10 minutos)
      cache-null-values: false

capitole:
  common:
    web:
      client:
        configs:
          starwars:
            # from Ms-Tenant
            # http://controlplane-server-ms-tenant-svc.controlplane.svc.cluster.local
            base-url: https://swapi.info

logging:
  level:
    org.zalando.logbook: TRACE
